In [2]:
print('hello world')

hello world


In [3]:
import pandas as pd
pd.__version__

'1.2.4'

In [4]:
data = {
    'IP' : 35000 ,
    'HW' : 30000 ,
    'SS' : 32500
}
sr = pd.Series(data)
sr

IP    35000
HW    30000
SS    32500
dtype: int64

In [5]:
import numpy as np
data2 = np.random.randint(10,100,6)
print(data2)

[10 46 73 25 45 63]


In [6]:
sr2 = pd.Series(data2)
display(sr2)

0    10
1    46
2    73
3    25
4    45
5    63
dtype: int32

In [7]:
a = [-3 , -5 , 1 , 0 , 3 , True , False]
b = [True , False , False]
c = np.array(a)
d = np.array(b)
print(c)
print(b)

[-3 -5  1  0  3  1  0]
[True, False, False]


In [8]:
a = [-3 , -5 , 1 , 0 , 3 , True , False]
b = [True , False , False]
c = np.array(a , dtype = bool)
d = np.array(b , dtype = float)
e = np.array(a , dtype = float)
print(c)
print(b)
print(e)

[ True  True  True False  True  True False]
[True, False, False]
[-3. -5.  1.  0.  3.  1.  0.]


In [9]:
a1 = np.random.randint(1 , 10 , (2,3))
a2 = np.random.randint(1 , 10 , (2,3))
s = np.concatenate([a1 , a2])
print(s)

[[2 2 6]
 [5 1 5]
 [2 4 5]
 [4 7 5]]


In [10]:
a3 = np.random.randint(1 , 10 , (2,2))
a4 = np.random.randint(1 , 10 , (2,3))
s2 = np.hstack([a3 , a4])
s3 = np.vstack([a3 , a3])
print(a3 , '\n')
print(a4 , '\n')
print(s2 , '\n')
print(s3)

[[1 7]
 [1 3]] 

[[3 5 2]
 [9 6 1]] 

[[1 7 3 5 2]
 [1 3 9 6 1]] 

[[1 7]
 [1 3]
 [1 7]
 [1 3]]


In [11]:
arr = np.random.randint(1 , 10 , (2,2))
print(arr , '\n')
arr2 = arr.view()
arr3 = arr.copy()
arr[0,0] = 137
print(arr , '\n')
print(arr2 , '\n')
print(arr3 , '\n')

[[8 9]
 [6 5]] 

[[137   9]
 [  6   5]] 

[[137   9]
 [  6   5]] 

[[8 9]
 [6 5]] 



In [12]:
data1 = [20,10,40,55]
sr1 = pd.Series(data1) #กำหนดข้อมูลแบบ sequence
data2 = (10,29,44,25,2)
sr2 = pd.Series(data2)
print(sr1 , "\n")

print(sr2 , "\n")

0    20
1    10
2    40
3    55
dtype: int64 

0    10
1    29
2    44
3    25
4     2
dtype: int64 



In [13]:
data3 = [10 , 30 , 20 , 33]
idx = ['a' , 'b' , 'c' , 'd'] #กำหนด index
sr3 = pd.Series(data3 , index = idx)
display(sr3)

a    10
b    30
c    20
d    33
dtype: int64

In [14]:
data4 = [10 , 30 , 20 , 33]
sr4 = pd.Series(data4 , index = list("abcd"))# ใข้ list กำหนด index
display(sr4)

a    10
b    30
c    20
d    33
dtype: int64

In [15]:
data5 = np.random.randint(10,100,5)
sr5 = pd.Series(data5 , index = [2,3,6,8,10])
display(sr5)

2     58
3     41
6     39
8     99
10    23
dtype: int32

In [16]:
display(sr5[3:8]) # เลือก index ตน.ที่ 3-8

8     99
10    23
dtype: int32

In [17]:
display(sr5.loc[3:8]) #เลือก index ที่ชื่อ 3-8

3    41
6    39
8    99
dtype: int32

In [18]:
display((sr5 > 30).all(),
       (sr5 % 10 ==0).any())

False

False

In [26]:
d1 = pd.Series([1,2,4] , index = list('abc'))
d2 = pd.Series([10,20] , index = list('cd'))
d3 = pd.concat([d1 , d2])
d4 = d1.append(d2 , ignore_index = False)
d5 = d1.append(d2 , ignore_index = True)
display(d3,
       d4,
       d5,
       d5.value_counts())

a     1
b     2
c     4
c    10
d    20
dtype: int64

a     1
b     2
c     4
c    10
d    20
dtype: int64

0     1
1     2
2     4
3    10
4    20
dtype: int64

10    1
1     1
2     1
20    1
4     1
dtype: int64

In [53]:
d6 = pd.Series(np.random.randint(10,100,10), index = list('abcdefghij'))
display(d6.head(3),
       d6.tail(3))
d7 = pd.Series([1,2,3,4] , index = list('abcd'))
#head(x) ==> เลือกตัวหน้ามา x ตัว
#tail(x) ==> เลือกตัวหลังมา x ตัว
display(d6.drop({'e','i'}))
#drop ==> มากกว่า 1 ตัวใส่ {}
d8 = d7.map({'a':10 , 'b':20})
d9 = d7.map({1:10 , 3:20})
display(d8,
       d9)
#display ==> ใส่เป็นชื่อ ตน. index ไม่ได้ ต้องใส่เป็นค่าข้อมูล
d10 = d7.rename({'a':'ant' , 'b':'boy'})
print(d10)
#rename => ต้องใส่ชื่อ index เท่านั้น(แก้ไขชื่อ index)

a    67
b    60
c    44
dtype: int32

h    47
i    49
j    69
dtype: int32

a    67
b    60
c    44
d    81
f    62
g    85
h    47
j    69
dtype: int32

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

a    10.0
b     NaN
c    20.0
d     NaN
dtype: float64

ant    1
boy    2
c      3
d      4
dtype: int64


In [58]:
s = pd.Series(np.random.randint(10,100,4) , index = list('abcd'))
for index, value in s.iteritems():
    print(f'{index}:{value}')

a:78
b:10
c:14
d:49


In [62]:
s2 = pd.Series(['A', 'B', 'C'])
for index, value in s2.iteritems():
    print(f"Index : {index}, Value : {value}")

Index : 0, Value : A
Index : 1, Value : B
Index : 2, Value : C


In [64]:
s3 = pd.Series([np.nan , 1,2,3,np.nan] , index = list('abcde'))
display(s3.sum(),
        s3.count(),
        s3.size)
#function การคำนวณไม่นับรวม nan แต่ size รวม nan ด้วย
#dropna() ==> ลบ nan ทิ้ง
#fillna() ==> เปลี่ยน nan เป็นค่าใหม่
#hasnans ==> return True Flase ตรวจสอบว่ามีค่า nan ?
s4 = s3.dropna()
s5 = s3.fillna(0)

display(s4,
       s5,
       s3.hasnans)

6.0

3

5

b    1.0
c    2.0
d    3.0
dtype: float64

a    0.0
b    1.0
c    2.0
d    3.0
e    0.0
dtype: float64

True