In [1]:
print('hello world')

hello world


In [2]:
import pandas as pd
pd.__version__

'1.2.4'

In [3]:
data = {
    'IP' : 35000 ,
    'HW' : 30000 ,
    'SS' : 32500
}
sr = pd.Series(data)
sr

IP    35000
HW    30000
SS    32500
dtype: int64

In [4]:
import numpy as np
data2 = np.random.randint(10,100,6)
print(data2)

[91 98 53 62 12 23]


In [5]:
sr2 = pd.Series(data2)
display(sr2)

0    91
1    98
2    53
3    62
4    12
5    23
dtype: int32

In [17]:
a = [-3 , -5 , 1 , 0 , 3 , True , False]
b = [True , False , False]
c = np.array(a)
d = np.array(b)
print(c)
print(b)

[-3 -5  1  0  3  1  0]
[True, False, False]


In [24]:
a = [-3 , -5 , 1 , 0 , 3 , True , False]
b = [True , False , False]
c = np.array(a , dtype = bool)
d = np.array(b , dtype = float)
e = np.array(a , dtype = float)
print(c)
print(b)
print(e)

[ True  True  True False  True  True False]
[True, False, False]
[-3. -5.  1.  0.  3.  1.  0.]


In [27]:
a1 = np.random.randint(1 , 10 , (2,3))
a2 = np.random.randint(1 , 10 , (2,3))
s = np.concatenate([a1 , a2])
print(s)

[[6 8 8]
 [3 7 3]
 [9 6 7]
 [3 5 7]]


In [39]:
a3 = np.random.randint(1 , 10 , (2,2))
a4 = np.random.randint(1 , 10 , (2,3))
s2 = np.hstack([a3 , a4])
s3 = np.vstack([a3 , a3])
print(a3 , '\n')
print(a4 , '\n')
print(s2 , '\n')
print(s3)

[[3 6]
 [7 6]] 

[[7 1 1]
 [5 7 7]] 

[[3 6 7 1 1]
 [7 6 5 7 7]] 

[[3 6]
 [7 6]
 [3 6]
 [7 6]]


In [42]:
arr = np.random.randint(1 , 10 , (2,2))
print(arr , '\n')
arr2 = arr.view()
arr3 = arr.copy()
arr[0,0] = 137
print(arr , '\n')
print(arr2 , '\n')
print(arr3 , '\n')

[[2 7]
 [8 4]] 

[[137   7]
 [  8   4]] 

[[137   7]
 [  8   4]] 

[[2 7]
 [8 4]] 



In [54]:
data1 = [20,10,40,55]
sr1 = pd.Series(data1) #กำหนดข้อมูลแบบ sequence
data2 = (10,29,44,25,2)
sr2 = pd.Series(data2)
print(sr1 , "\n")

print(sr2 , "\n")

0    20
1    10
2    40
3    55
dtype: int64 

0    10
1    29
2    44
3    25
4     2
dtype: int64 



In [56]:
data3 = [10 , 30 , 20 , 33]
idx = ['a' , 'b' , 'c' , 'd'] #กำหนด index
sr3 = pd.Series(data3 , index = idx)
display(sr3)

a    10
b    30
c    20
d    33
dtype: int64

In [57]:
data4 = [10 , 30 , 20 , 33]
sr4 = pd.Series(data4 , index = list("abcd"))# ใข้ list กำหนด index
display(sr4)

a    10
b    30
c    20
d    33
dtype: int64

In [67]:
data5 = np.random.randint(10,100,5)
sr5 = pd.Series(data5 , index = [2,3,6,8,10])
display(sr5)

2     27
3     13
6     28
8     38
10    49
dtype: int32

In [68]:
display(sr5[3:8]) # เลือก index ตน.ที่ 3-8

8     38
10    49
dtype: int32

In [69]:
display(sr5.loc[3:8]) #เลือก index ที่ชื่อ 3-8

3    13
6    28
8    38
dtype: int32